@backend_HostAddress = http://localhost:5173

###
POST {{backend_HostAddress}}/files
content-type: application/json
{
    "Id": 1,
    "Name": "TestFile1",
    "DueDate": "2024-04-09",
    "FileType": "PDF",
    "IsIndexed": false
}
###
GET {{backend_HostAddress}}/
Accept: application/json

GET {{backend_HostAddress}}/files
Accept: application/json

GET {{backend_HostAddress}}/documents/1
Accept: application/json
###
DELETE {{backend_HostAddress}}/files/1